### ISSUE TITLE
SMS messaging

### ISSUE THREAD

**Issue by angipp01** [REHolt/Garage-Door#5]
So this is what I have done with the script.  I have compared with 'Hammer Project' and can't figure why the script is not sending me the text message.   I know the URL works because when I manually enter it into the browser I receive a text message.

pinMode(1, OUTPUT); // I was trying to figure out what was GPIO 1
digitalWrite(1, HIGH); // Don't know what GPIO 1 does.,It has something with SMS

pinMode(Door1Status1, INPUT_PULLUP);
attachInterrupt(digitalPinToInterrupt(Door1Status1), Status1, CHANGE);
pinMode(Door1Status2, INPUT_PULLUP);
attachInterrupt(digitalPinToInterrupt(Door1Status2), Status1, CHANGE);

// SMS, It is very close to your verison
void sendSms(String message) {
HTTPClient http;

http.begin(iftttMakerUrl, "‎c0 5d 08 5e e1 3e e0 66 f3 79 27 1a ca 1f fc 09 24 11 61 62");

http.addHeader("content-type", "application/json");
int result = http.POST("{\"value1\":\"" + message + "\"}");

http.end();
}

void checkOpen() {
if ( digitalRead(Door1Status1) == doorOpen ) {
digitalWrite(1, LOW); delay(1000); digitalWrite(1, HIGH); delay(500); digitalWrite(1, LOW); delay(1000); digitalWrite(1, HIGH);
doorOpenDurationInSeconds += 5;
}
if (digitalRead(Door1Status2) == doorClosed) {
digitalWrite(1, LOW); delay(1000); digitalWrite(1, HIGH); delay(500); digitalWrite(1, LOW); delay(1000); digitalWrite(1, HIGH);
resetDoorOpenCounter();
}
//if ( digitalRead(Door2Status1) == doorOpen ) {
// doorOpenDurationInSeconds += 5;
// } 
// if (digitalRead(Door2Status2) == doorClosed) {
// resetDoorOpenCounter();
// }

if ( messageSentInThisOpening == false &&
doorOpenDurationInSeconds > openForTooLongInMins * 60 ) {
String messageToSend = (String)"WARNING: your garage door has been open for more than " + openForTooLongInMins + " mins!";
sendSms(messageToSend);

doorOpenDurationInSeconds =0;
// todo: this does not know if it sent successfully. needs work
messageSentInThisOpening = true;
}
}

**Comment by angipp01** [comment]
[garage door sms-not wrkng.txt](https://github.com/REHolt/Garage-Door-Controller/files/756296/garage.door.sms-not.wrkng.txt)

**Comment by REHolt** [comment]
I will try and look at this later this week. The text message is working on my garage door opener, so I know the code is right. 

Did you enter the IFTT Key code? You might want to be sure it is entered correctly.

**Comment by angipp01** [comment]
When I added the url to the browser it sends me a text, but when when I have Arduino to it, it doesn't work. 
I had the door contact together to identify the door is 'open' and changed the timer for 1 min but no text.

"https://maker.ifttt.com/trigger/esp_message/with/key/eFcxJ06w9B6kR3pxJz2a0iRg5ozl-uo------------";

This feature is terrific! It is basically your own security system.

**Comment by REHolt** [comment]
I agree, I have been using it on my garage door for awhile now. It reminds me if I leave the garage door open for over an hour. If I leave the house and forget to close it, or something was in the way and it didn't close, I get a text message. I can always call my son and get him to go by and close it.

I'll take a look and see if I can see whats wrong.

**Comment by REHolt** [comment]
Looking over the code some today and making notes in the file as I see thing I'm not sure of. I gather, from you changes, that you are using GPIO 1 as sort of a test bit? it looks like it is being used in the check status routine to flash an LED and time the door is identified as open or closed?

It also looks like there is only  one Door open Timer. the same counter is used for door one and door 2. if this is the case, then if either door is found to be closed, the counter will be set back to "0" and no message will be sent. It would be best to duplicate the counter code and make separate counters for door 1 and 2. 

It also appears you have two variables identified for the same GPIO pin. Door1Enable  and Door1Trigger are both defined to GPIO 4 and Door2Enable  Door2Trigger are both defined to GPIO 14; WHY? I only see a PINMODE statement for the Door1Enable and Door2Enable, but you use the Door1Trigger variable in the main portion of the code as part of a digitalWrite command. Not sure I really understand why you would do that? Since the pinmode was defined as part of another statement, you should still be able to use the output pin, but why not just use the Door1Enable variable?

I brought one of the Garage Door Opener circuits with me, so I will try hooking it up later and seen if I can trace through the code to verify where it is getting hung up.

**Comment by angipp01** [comment]
Ya regarding the GP0 1  (I have no idea what it was used for.  I compared code from Hammer site, and compared the difference.  Hammer site had the code, so I also added it in figuring if this was the issue. 

"It also looks like there is only one Door open Timer. the same counter is used for door one and door 2. if this is the case, then if either door is found to be closed, the counter will be set back to "0" and no message will be sent. It would be best to duplicate the counter code and make separate counters for door 1 and 2."
Ah, I didn't know this. 

Door1Trigger  are only used for the Website.  (at the time of experimenting and developing the HTTP site, I have created "Door1Trigger" to have it easier for me to code)  Ya, I can see, it was an unnecessary duplication. 

I want to supply you the most currenty .txt file     

I will remove GPO = 1   (didn't know what it did anyways.)
I will also remove   Door#Trigger and replace with Door#Enable

I will supply you the file approx 6 EST

Thanks.

**Comment by angipp01** [comment]
[garage door sms-not wrkng.txt](https://github.com/REHolt/Garage-Door-Controller/files/772661/garage.door.sms-not.wrkng.txt)

Here is the updated file that SMS doesn't work.  
I have edited the code as per your recommendation since they are irrelevant duplication..

**Comment by angipp01** [comment]
> It also looks like there is only one Door open Timer. the same counter is used for door one and door 2. if this is the case, then if either door is found to be closed, the counter will be set back to "0" and no message will be sent. It would be best to duplicate the counter code and make separate counters for door 1 and 2.

Now I understand logic about the second timer, but I have excluded the Door 2 from my code using "//" and still didn't work for Door 1"

FYI most current SHA-1 is:
http.begin(iftttMakerUrl, "‎c0 5d 08 5e e1 3e e0 66 f3 79 27 1a ca 1f fc 09 24 11 61 62");

Again thanks for your help.

**Comment by REHolt** [comment]
Just got back from a nice Seafood Restaurant and am settled back with a glass of Jack Danial's on ice. I have the garage door opener hooked up and will try to trace through the code. Hopefully I can come up with something.

**Comment by REHolt** [comment]
Looking at your latest file; In your "checkOpen" routine, there is an error. the statement

 if ( messageSentInThisOpening == false &&
  doorOpenDurationInSeconds > openForTooLongInMins * 2 ) {

should read

 if ( messageSentInThisOpening == false &&
  doorOpenDurationInSeconds > openForTooLongInMins * 60) {

the multiplier "60" is converting your "openForTooLongInMins" variable to seconds since the timer counts in seconds. When You changed the variable to a "2" the software thinks you want an SMS text sent after only 4 seconds.

The routine appears to be working, in that it actually calls the "sendSms" routine.  The fact that it doesn't get sent could be a couple of issues. Either the "ifttMakerUrl" in the Keys file is wrong, or code is wrong (http.begin(iftttMakerUrl, "?c0 5d 08 5e e1 3e e0 66 f3 79 27 1a ca 1f fc 09 24 11 61 62")).

not sure which it could be right now. 

I'll have to go back to the iftt site or the original code at the Hammer site. It's been awhile since I set mine up and I don't remember all of the details.

**Comment by angipp01** [comment]
Ah  I thought the 60 meant  the door needs to be open for 60mins for me to get the text message.  So for trail reasons I changed it to 2 mins .   HA HA   
I will change to 60.

Thanks

**Comment by REHolt** [comment]
The door status routine seems to be working. I can force the sensor pins low and it reports the door is closed.  Wen i let the sensor pin go high, it reports the door "partially open". once the timer counts to 120 seconds it calls the SMS routine. if i leave it high, it only calls the SMS routine once. If I pull it low, the timer stops.

the only thing that is not working is the IFTTT statement, so the error is in what is being sent to ifttt to request an sms.

**Comment by angipp01** [comment]
Ya something is wrong.  I will look it over again.  no text yet. 
Which one do you have?

http.begin(iftttMakerUrl, "‎c0 5d 08 5e e1 3e e0 66 f3 79 27 1a ca 1f fc 09 24 11 61 62");
or
http.begin(iftttMakerUrl, "A9 81 E1 35 B3 7F 81 B9 87 9D 11 DD 48 55 43 2C 8F C3 EC 87");


Also, should the routine be like this? Using  Door1Status1
void checkOpen() {
  if (digitalRead(**Door1Status1**) == doorOpen) {
     doorOpenDurationInSeconds += 5;
  }
if (digitalRead(**Door1Status1**) == doorClosed) {

**Comment by REHolt** [comment]
I've tried both, " http.begin(iftttMakerUrl, "A9 81 E1 35 B3 7F 81 B9 87 9D 11 DD 48 55 43 2C 8F C3 EC 87");" is the one I have in my other garage door opener and it has worked in the past. I haven't tried it lately, and I'm not home to give it a go. 

IFTTT wont let me test the message right now.

**Comment by REHolt** [comment]
Did you ever figure out how to place an actual button on the web page? I would like to have a button rather than just a hyperlink.

**Comment by angipp01** [comment]
Ya I had a button before.  I can put it back on.    The only thing I fear with the button is that it will be very small on a phone.  I will test it out. 
The one issue I am having is that the Arduino crashes sometimes for an unknown reason when accessing the webpage randomly.
I got the text working...  
I think I know what the problem was.  When Flashing the Arduino I had the contacts in the Door open position, and waited and waited for my text to arrive.  But, If I start in the Door Closed position and then change it to door open or Partially open it then sends a text.

by the way,  i am using 
http.begin(iftttMakerUrl, "C0 5D 08 5E E1 3E E0 66 F3 79 27 1A CA 1F FC 09 24 11 61 62");

Wednesday I will add the buttons.  ( will sent you a .txt)
I have also have the main page (Full) to be refreshed every 20 sec) hopfully this will fix the crash.

**Comment by REHolt** [comment]
Thanks, I couldn't even get IFTTT to send me a test SMS text last night. It said it did, but I never received it. I never had that problem when I first developed the code. Maybe they were doing maintenance or something. I'll give it a try today. I think I may have screwed up my other door opener, The system seems to have re-generated the KEY code. I'll need to test that when I get home too. 

There also seems to be a spurious web page access. When I was testing yesterday I would sometimes get a "new client, GET / HTTP/1.0 Invalid  request" message, even though I never sent a web request. 

I just tried the Text this morning and it  work for me using "C0 5D 08 5E E1 3E E0 66 F3 79 27 1A CA 1F FC 09 24 11 61 62".  turns out I had a typo, there was a "?" at the beginning of the above code. I now get a text message. 

Where did you find the information about that code changing? Do you know why it changed?

**Comment by angipp01** [comment]
> "new client, GET / HTTP/1.0 Invalid request" message, even though I never sent a web request.
Ya I saw this, I don't know what it means.  But I was thinking, well its working.

> Where did you find the information about that code changing? Do you know why it changed?
I read comments after comments in the Hammer site.  Some one explains how to look up the 'fingerprint (or I think it is called thumbprint)  Then I googled it 'How to find Fingerprint on page'.   It gave me direction for Safari browser.  So then I downloaded Safari browser and followed the instructions and clicked on the 'lock' in the URL and clicked on everything in the Certification information untill I found a Hex code.

**Comment by angipp01** [comment]
Another option I want to do. (you have already enabled it on the Arduino)  Create a DNS.  This means instead of entering 192.168.2.x/Full  or 192.168.0.x/Full  (the problem is you need to remember the ip address of the site depending on what router it is connected to.  This will become difficult once you begin to design to your friends.  But DNS solves this problem.   you can name your device as 'garagedoor'.  Therefore, all you need is to enter URL  garagedoor/Full  to access the page.  This will simplify things for the user.

**Comment by angipp01** [comment]
this is odd, it doesn't send me messages when the door is open, but it will send me messages when the door is partially open.  I don't understand why.

**Comment by REHolt** [comment]
Probably something in the logic about checking both sensors. I kind of moved away from that on the "Generic" garage door code. Most people don't care about having two sensors, it doesn't matter if it is "Partially Open". That still means it is open.

**Comment by REHolt** [comment]
"Create DNS" would be an interesting feature to add. I had thought of that early on, but never went back to fully implement the capability. It looks like the ESP8266mDNS.h library is only designed to work the the Bonjour web browser. Maybe there is an alternate solution.

**Comment by angipp01** [comment]
OK I will delete the code  and just have it generic.  Hopefully this will solve the SMS messaging when it only sends on Partially open (agree it is still open. Keep it simple).    [To remove this section of code is confusing (it is actually the most confusing section of the code)]  Can you send me a revised copy of .txt file from my file i gave you yesterday?

> "Create DNS" would be an interesting feature to add. I had thought of that early on, but never went back to fully implement the capability. It looks like the ESP8266mDNS.h library is only designed to work the the Bonjour web browser. Maybe there is an alternate solution.
Prior sending the .txt file to you yesterday I had code for ESP8266mDNS.  I removed it for 2 reasons.  
1. Didn't want to complicate things.  (my importance was to solve this garage door SMS)
2. Not working 
I have been watching Youtube Video.
https://www.youtube.com/watch?v=ewrF1LzrxH8

Tomorrow I will supply u code for buttons.  I am going to have the buttons centered on the screen.

**Comment by angipp01** [comment]
[working SMS.txt](https://github.com/REHolt/Garage-Door-Controller/files/778941/working.SMS.txt)

Ok I have centered the buttons, but don't know how to centered the status.  Although I don't mind it on the side.

Also I changed a little of the code logic to have my contacts to work correctly and send me a text message when the door is open and not send me a text message when the door is closed.
const int doorOpen = LOW;
const int doorClosed = HIGH;


Also please look at my code for the doorstatus1 to see if I correctly removed the 'partially open' code.  It seems that I have it corrected.  When it is neither open or closed the result is = "unknown".  

I guess we can close this issue.  for SMS.  

Next week I will work on DNS naming the board.  It will make life easier not to edit the ip address in the code.  (sometimes I bring it to work.  it is a pain to log into the router to find the ip address of the router.)

I will wait on your comments of my file I have supplied to see if I omitted the code correctly for partially open.

**Comment by REHolt** [comment]
Just saw this, I will be traveling home today, so I will be driving most of the day. I will be working some of this this weekend as well, so hopefully I'll have time to look over your code. I'll get back to you with comments when I can.

**Comment by REHolt** [comment]
I have looked over your code and made a few changes. I fixed the door open timers to check each door separately. I don't have a system set-up for two doors, so I can't fully check it, but it works for one door.

The only part that needs to be fixed now is where you explicitly call out the ip address:

else if (req.indexOf("/Full") != -1){  //brings to Webpage 192.XXX.X.XX/Full 

This should be done using a variable set using the WiFi.localIP() command. I'm not sure how to do this, but will look into it later today or sometime this week. 

I am attaching 2 files. The first is your file with my corrections. The second is your file with an additional change. This change will allow you to connect up to any wifi domain. It sets up it's own DNS server, with a captive web page. you can enter the credentials on the web page and it will save them to internal device memory. It would be a great tool if you are making a door opener (or anything else web enabled) for a friend. That way they wouldn't have to give you their login and password and you wouldn't have to hard code it into the software or even the KEYS file. everyone would have the exact same software. That would be a lot easier to manage. in order for it to fully work though, we need to fix the problem above.

[2Door_SMS_working.txt](https://github.com/REHolt/Garage-Door-Controller/files/785995/2Door_SMS_working.txt)
[2DoorGarageOpenerwithConfig.txt](https://github.com/REHolt/Garage-Door-Controller/files/785996/2DoorGarageOpenerwithConfig.txt)

**Comment by angipp01** [comment]
[arduino1357.pdf](https://github.com/REHolt/Garage-Door-Controller/files/788716/arduino1357.pdf)

I have implemented a 3rd door contact called Status3.  For now I have disabled everything that involves the 3rd door because I don't know how to implement the 'Switch Case'

//void Status3() {
//  Status_Open = digitalRead(ExitStatus);
//  Status_Closed = digitalRead(Door2Status2);
//  switch (Status_Open) {
//  case 0:
//  {
//  switch (Status_Closed) {
//  case 0:
//  {
//  Door3_Status = "Closed";
//  }
//  break;
//  case 1: {
//  Door3_Status = "Open";
//  }
//  break;
//  }
//  }
//  break;
//  case 1:
//  {
//  switch (Status_Closed) {
//  }
//  }
//  }
//  }
 
I know it is a lot of repetitive steps but keeping everything separate.

[Feb 20.txt](https://github.com/REHolt/Garage-Door-Controller/files/788724/Feb.20.txt)

**Comment by REHolt** [comment]
Try this. The case statement for the Exit door didn't need to be as complicated as the other two. Door 1 and Door 2 were set up with 2 sensors each, so there were nested Case statements in order to check the status of each sensor. The Exit door only has one sensor, so there are only two possible states.

There were also some problems in the SMS routine. I fixed them but may have introduced something else. I think the routine continues to send Text messages every minute. It should only send one message each time the door is left open. Closing the door should reset it for the next time the door stays open too long.

I will look at this further tomorrow

[2DoorGarageOpenerwithExitDoor.txt](https://github.com/REHolt/Garage-Door-Controller/files/789046/2DoorGarageOpenerwithExitDoor.txt)

**Comment by angipp01** [comment]
Sorry,  I haven't tested this yet.    I hope I will get a chance to look at this tomorrow or Friday .  Maybe Friday, with a glass wine.  Can't wait till Friday.  Weather getting warmer and snow is melting.  It is beginning to get comfortable to be outside, therefore, I will be soon be installing the unit.

**Comment by REHolt** [comment]
Here is an update. It's not finished yet, but I have been working on defining the size of the button. I managed to come up with the proper commands to set the size and color, but now it won't center the button. Maybe you can figure out how to center it. it seems to be dependent on the order that the commands are listed.

[2DoorGarageOpenerwithConfig.txt](https://github.com/REHolt/Garage-Door-Controller/files/795510/2DoorGarageOpenerwithConfig.txt)
 
Still have not gotten the text size to work. I have tried a couple of different HTML methods, but it just doesn't work.

**Comment by angipp01** [comment]
Sorry to say, the buttons are center for me.  
I have an issue when viewing on the phone.  The buttons are small.  So I increased the value of the button dementions but the button size stayed the same.   So I googled it.  I found others having the same problem and resolved the issue.  So I added the code to yours and it worked.  Also I have centered everything.  I don't know if you want it that way or not.  

[Feb 23.txt](https://github.com/REHolt/Garage-Door-Controller/files/798340/Feb.23.txt)


![img_2933](https://cloud.githubusercontent.com/assets/21009036/23290034/e1e5fd14-fa1b-11e6-847a-d7ecadd485b8.PNG)

**Comment by REHolt** [comment]
Looks good. The commands look the same as what I provided the other day. Not sure why it didn't work on my system. I have been reading some stuff on HTML, but I guess I don't understand it yet. I will make your modifications to mine and see what happens. I like the layout and will use it in the future as the web interface for my Garage Door Opener. That should help with the friend who has an iPhone. He can use the browser interface instead of an app.

Thanks for the help.

**Comment by REHolt** [comment]
I updated my software with your HTML commands and was able to set the button to center. I also was able to set the text size inside the button using the following command:

client.println("<input type=button margin:auto;display:block value=Garage_Door style=font-size:130%;width:200px;height:90px;background-color:blue  onmousedown=location.href=\"/gpio/3\">"); 

I also wanted to change the text size of the title and status; but I can't tell from you HTML code where that value gets set. I tried using the same "style=font-size:130%" command but no matter were I placed it, there was no effect. Can you show me were that information is placed? 

Enabling DNS would help too, since you would be able to call it by name rather than using the full ip address. still working on that though (maybe after I change the oil in my car today).

**Comment by angipp01** [comment]
Ok, html is pretty simple.
 it usually has an open and closed code.  for example:
beings= <font>    ends  </font>
beings= <center>    ends </font>
<head>   </head>
<body> </body>
The open an closed codes doesn't need to be on the same line.  For example if you want a paragraph centered you put the <center><p> in the beginning and </p></center> at the end  ("p" is for paragraph)

So now you need to look at the "H"   You will see <h2>   You can change the size by changning the value (the higher the number the bigger the font)  for example H1 is the biggest.
Note: Remember:  you need to change both beginning and end html code  <h2> & </h2>  So what ever is in between the code will be affected.

**Comment by angipp01** [comment]
lol  my comments with html code affected the appearance when i submitted it.

**Comment by angipp01** [comment]
[html.txt](https://github.com/REHolt/Garage-Door-Controller/files/800006/html.txt)

**Comment by REHolt** [comment]
I modified the HTML a little bit. Changed the background and text color. Mostly just to show myself I could. Your right about the html code, being fairly simple, but figuring out where and how to place the color and size parameters took a bit of trial and error. I now have a much better understanding and can write a much more flexible web interface. There are still a couple of items I want to change, but just taking baby steps for now.

[2DoorGarageOpenerwithConfig.txt](https://github.com/REHolt/Garage-Door-Controller/files/801229/2DoorGarageOpenerwithConfig.txt)

**Comment by angipp01** [comment]
That is good.  See, HTML is kinda easy.  HTML is very forgiving it is not like C++ where some lines have ; or { or } or strings.  I am getting the hang of reading the code, but not at the level of designing it. 

Since the partially open have been removed.  The door status function normally with 1 status int per door.  Yes it is optional to connected the open contact but if the contact has moved off of 'closed' the website will read 'open' anyways.

**Comment by angipp01** [comment]
So it is my first time that I have used OTA.  Yes I was still doing everything over serial .  I got my port to point to the network 192.168.1.59.  But when I upload I get this:  (Yes I did download Phython which i am able now to see my network.

java.io.IOException: Cannot run program "python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.GenericNetworkUploader.uploadUsingPreferences(GenericNetworkUploader.java:97)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.Sketch.upload(Sketch.java:1187)
	at processing.app.Sketch.exportApplet(Sketch.java:1160)
	at processing.app.Sketch.exportApplet(Sketch.java:1132)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2409)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more
An error occurred while uploading the sketch

**Comment by angipp01** [comment]
never mind solved.

**Comment by sreeramtkd** [comment]
@angipp01 How did you solve the upload issue ? I'm getting the same error, using the latest IDE 1.8.5 & I've also installed Python 3.6. Appreciate any help !

java.io.IOException: Cannot run program "python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.GenericNetworkUploader.uploadUsingPreferences(GenericNetworkUploader.java:99)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.SketchController.upload(SketchController.java:713)
	at processing.app.SketchController.exportApplet(SketchController.java:686)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2168)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)

**Comment by angipp01** [comment]
Unfortunately about 4 months after this program was complete, I zapped (overloaded my board) and I haven't replaced it yet.  So I wouldn't be able to answer you.  I might so able to answer you in the coming weeks when I am building a new project with similar concept.  It will be a water detection sensor with push text alert.

**Comment by REHolt** [comment]
sreeramtkd 

I just saw this, as I have not messed with the Garage Door Opener for about a year. Mine is still working in my Garage. 

I have not updated to IDE 1.8.5 or the latest Pytho 3.6 As I recall some of these libraries did not work under 3.6. That was some time ago, maybe they have fixed them now. I may try to download the latest version and see what affect it has. I have someone who would like me to build them one of these, so it might be a good time to update everything. If it does not work, it will likely be a couple of weeks before I come up with a solution. I have not done any work with the ESP866 in most of a year.

**Comment by REHolt** [comment]
I just installed IDE 1.8.5 and checked the garage door software. Using the "Verify" button in the top left corner It seems to compile just fine. i did not have a board connected, but it should not have a problem loading to the ESP8266. 

Using 1.8.5 I no longer have the option for OTA programming. I'll look into this further to see what I can find.

**Comment by REHolt** [comment]
I just got the OTA working again. It seems that with the new IDE the Over The Air(OTA) programming is using the Bonjour protocol which is using MulticastDomainNameService(mDNS). So I installed the Bonjour browser for Windows and now I have access to my ESP8266 devices again through OTA.
